[package]
name = "fsrep"
version = "0.2.0"
authors = ["Tyler Adam Martinez <TylerAdamMartinez@outlook.com>"]
description = "A grep alternative written in rust"
license = "GPL-2.0-only"
edition = "2021"

[dependencies]
colored = "2"
regex = "1.5.5"
